/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JudgeService */

#ifndef _Included_JudgeService
#define _Included_JudgeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JudgeService
 * Method:    sandbox
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JudgeService_sandbox
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
